[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_port = COM9
monitor_port = COM9

lib_deps =
    bblanchon/ArduinoJson@^6.19.4
    knolleary/PubSubClient@^2.8
    marvinroger/AsyncMqttClient@^0.9.0
    mathieucarbou/AsyncTCP@^3.2.4
    mathieucarbou/ESPAsyncWebServer@^3.3.17

monitor_speed = 115200
upload_speed = 921600
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DMQTT_MAX_PACKET_SIZE=1024

[platformio]
default_envs = nodemcu-32s
